name: Ping Render App

on:
  schedule:
    - cron: '*/5 * * * *'  # Cada 5 minutos
  workflow_dispatch:       # También puedes correrlo manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer ping al backend
        run: curl -s https://prestamos-back.onrender.com